### ISSUE TITLE
Incorrect state after set hvac_modes to off

### ISSUE THREAD

**Issue by tabletka-ao** [neffs/ha-cometblue#16]
Home Assistant 2022.8.7
Supervisor 2022.08.3
Operating System 8.5

Thermostat model_type: COBL0133

After set HVAC_MODE to off by thermostat card on the thermostat state is OK (setting to off), but state of entity in hassio is incorrect because is set to heat

`DEBUG (MainThread) [custom_components.cometblue.climate] HVAC_MODE to set: off
DEBUG (MainThread) [cometblue_lite.cometblue] Updating Temperatures to {'current_temp': -128, 'manual_temp': 15, 'target_temp_l': -128, 'target_temp_h': -128, 'offset_temp': -128, 'window_open_detection': -128, 'window_open_minutes': -128}
DEBUG (MainThread) [cometblue_lite.cometblue] Successfully updated Temperatures for device b0:36:27:55:eb:70
DEBUG (MainThread) [cometblue_lite.cometblue] Updating Status to {'manual_mode': True}
DEBUG (MainThread) [cometblue_lite.cometblue] Updating Status to {'manual_mode': True}
DEBUG (MainThread) [cometblue_lite.cometblue] Successfully updated status for device b0:36:27:55:eb:70
DEBUG (MainThread) [cometblue_lite.cometblue] Got invalid Temperatures: (-128, 15, -128, -128, -128, -128, -128)
DEBUG (MainThread) [cometblue_lite.cometblue] Successfully fetched new readings for device b0:36:27:55:eb:70`

![image](https://user-images.githubusercontent.com/60447568/187194294-5c0970a0-f752-43e0-b191-22b27095a125.png)

**Comment by neffs** [comment]
The device sometimes gives back what we wrote to the device, instead of the correct temperatures. This is a firmware bug. I figured the best way to handle this is to ignore the read temperature values. Therefore we can't fully update the state. It should update with the next read.

Off is just manual/heat with a temperature of 7.5 degrees.

I'm closing this. If you have a good idea how to improve this feel free to post a PR.

**Comment by tabletka-ao** [comment]
@neffs 
maybe 
`        # preserve current "target_temperature" when TEMPERATURE_OFF is active
        if manual_temp != -128:
          if manual_temp / 2.0 == CometBlueStates.TEMPERATURE_OFF:
              self.is_off = True
          else:
              self.is_off = False
              self.target_temperature = manual_temp / 2.0
        if current_temp != -128:
            self._current_temp = current_temp / 2.0
        if target_low != -128:
            self.target_temp_l = target_low / 2.0
        if target_high != -128:
            self.target_temp_h = target_high / 2.0
        if offset_temp != -128:
            self.offset_temperature = offset_temp / 2.0
        if window_open_detect != -128:
            self.window_open_detection = window_open_detect
        if window_open_detect != -128:
            self.window_open_minutes = window_open_minutes
        _LOGGER.debug("Got Temperatures: {}".format(temps))`

**Comment by tabletka-ao** [comment]
@neffs Are you right, after the next read the state of entity is correctly.

Maybe `if -128 in temps:` then check state of device again (single loop)? 
https://github.com/neffs/python-cometblue_lite/blob/601582b766023f772cc3cc202609eddd23e54ef8/cometblue_lite/cometblue.py#L225

or comeback to below ?

`        # preserve current "target_temperature" when TEMPERATURE_OFF is active
        if manual_temp != -128:
          if manual_temp / 2.0 == CometBlueStates.TEMPERATURE_OFF:
              self.is_off = True
          else:
              self.is_off = False
              self.target_temperature = manual_temp / 2.0
        if current_temp != -128:
            self._current_temp = current_temp / 2.0
        if target_low != -128:
            self.target_temp_l = target_low / 2.0
        if target_high != -128:
            self.target_temp_h = target_high / 2.0
        if offset_temp != -128:
            self.offset_temperature = offset_temp / 2.0
        if window_open_detect != -128:
            self.window_open_detection = window_open_detect
        if window_open_detect != -128:
            self.window_open_minutes = window_open_minutes
        _LOGGER.debug("Got Temperatures: {}".format(temps))`
