### ISSUE TITLE
Not compatible with HA 2022.7 and above

### ISSUE THREAD

**Issue by damsma** [neffs/ha-cometblue#18]
In Home Assistant 2022.7 the bluepy library is not working anymore.

https://www.home-assistant.io/blog/2022/07/06/release-20227/#breaking-changes

do you plan to migrate this great plugin to the bleak library?

https://pypi.org/project/bleak/

Errors in log:
`2022-09-14 23:57:31.486 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package cometblue_lite==0.4.1: error: subprocess-exited-with-error
× python setup.py bdist_wheel did not run successfully.
│ exit code: 1
╰─> [8 lines of output]
/usr/local/lib/python3.10/site-packages/setuptools/dist.py:772: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
warnings.warn(
running bdist_wheel
running build
running build_py
Working dir is /tmp/pip-install-oj9gi1v9/bluepy_fc238c469c4046dfbac1e7d85a2175f7
execute make -C ./bluepy clean
error: [Errno 2] No such file or directory: 'make'
[end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for bluepy
error: subprocess-exited-with-error
× Running setup.py install for bluepy did not run successfully.
│ exit code: 1
╰─> [10 lines of output]
/usr/local/lib/python3.10/site-packages/setuptools/dist.py:772: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
warnings.warn(
running install
/usr/local/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
warnings.warn(
running build
running build_py
Working dir is /tmp/pip-install-oj9gi1v9/bluepy_fc238c469c4046dfbac1e7d85a2175f7
execute make -C ./bluepy clean
error: [Errno 2] No such file or directory: 'make'
[end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure
× Encountered error while trying to install package.
╰─> bluepy
note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.`

**Comment by neffs** [comment]
Already done. Just update to the latest version.
