### ISSUE TITLE
HA 2024.1 - Integration not working anymore

### ISSUE THREAD

**Issue by renekuehl** [neffs/ha-cometblue#20]
Since updating to 2024.1 of HA , the Integration doesn't work anymore. The Errors I get in the Logs are : 

Logger: custom_components.cometblue.climate
Source: custom_components/cometblue/climate.py:243
Integration: cometblue (documentation)
First occurred: 21:50:50 (150 occurrences)
Last logged: 22:14:50

Updating the state for D5:15:61:D4:65:7C failed: Argument 'address' has incorrect type (expected str, got NodeStrClass)
Updating the state for E8:C9:CA:B3:BB:AC failed: Argument 'address' has incorrect type (expected str, got NodeStrClass)
Updating the state for 60:9B:32:2F:B9:DB failed: Argument 'address' has incorrect type (expected str, got NodeStrClass)
Updating the state for 26:44:32:A1:CD:DF failed: Argument 'address' has incorrect type (expected str, got NodeStrClass)
Updating the state for 3C:A8:0B:75:FC:30 failed: Argument 'address' has incorrect type (expected str, got NodeStrClass)

---------------------------

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1520
First occurred: 21:49:50 (19 occurrences)
Last logged: 21:49:51

Entity None (<class 'custom_components.cometblue.climate.CometBlueThermostat'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature.TARGET_TEMPERATURE: 1>, please report it to the author of the 'cometblue' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
Entity None (<class 'custom_components.hacs.update.HacsRepositoryUpdateEntity'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <UpdateEntityFeature.INSTALL|PROGRESS|RELEASE_NOTES: 21>, please create a bug report at https://github.com/hacs/integration/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

I hope this Integration is still under Maintenance. It served me so well during the last Year using ESP32 Bluetooth Proxies.... 

Thx in Advance if anyone can correct this ...

**Comment by neffs** [comment]
This issue could also be a bug in Home Assistant. This could be related:
https://github.com/home-assistant/core/issues/107185

As a temporary fix you could try to replace change line 79  in climate.py to: 
`        dev = CometBlueThermostat(str(device_cfg[CONF_MAC]), name, str(device_cfg[CONF_PIN]))
`

I dont have a working thermostat right now, to check myself. Sorry!

**Comment by renekuehl** [comment]
Thank you. But the Errors seems to continue. I changed line 79, but the Errors in the Logs are now:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.cometblue.climate
Source: custom_components/cometblue/climate.py:243
Integration: cometblue (documentation)
First occurred: 10:00:11 (5 occurrences)
Last logged: 10:00:54

Updating the state for D5:15:61:D4:65:7C failed: required argument is not an integer
Updating the state for 60:9B:32:2F:B9:DB failed: required argument is not an integer
Updating the state for 3C:A8:0B:75:FC:30 failed: required argument is not an integer
Updating the state for E8:C9:CA:B3:BB:AC failed: required argument is not an integer
Updating the state for 26:44:32:A1:CD:DF failed: required argument is not an integer

Man, I wish I wouldn't have stopped Programming after the Atari ST :D

**Comment by neffs** [comment]
Oops, pin should be an int.
At least there is no error for the address, so we should be on the right track:

dev = CometBlueThermostat(str(device_cfg[CONF_MAC]), name, int(device_cfg[CONF_PIN]))

**Comment by Chameo71** [comment]
This works (for me)! Thanx for your fast response!

**Comment by renekuehl** [comment]
The Thermostats are coming back online. Thank you Neffs :)

**Comment by renekuehl** [comment]
The Thermostats are coming back online. Thank you neffs :100: :+1:
