### ISSUE TITLE
Negative current temperater right after adjusting

### ISSUE THREAD

**Issue by DenisBY** [neffs/ha-cometblue#6]
Right after setting temperature via HA it shows current temperature as -128:
![image](https://user-images.githubusercontent.com/1147703/82048411-ea746e00-96b4-11ea-80f3-7afb6313c593.png)
![image](https://user-images.githubusercontent.com/1147703/82048642-4b9c4180-96b5-11ea-8633-180c133d0e29.png)
After some time (on next poll I guess) it shows correct temperature.
Please let me know if you need more information.

**Comment by neffs** [comment]
Somehow the device returns garbage values after you write new temperature to it. Should be fixed now. Thanks for reporting this!

**Comment by DenisBY** [comment]
Thanks! Now it works perfect!
