### ISSUE TITLE
[feature request] Provide sensor for current temperature

### ISSUE THREAD

**Issue by DenisBY** [neffs/ha-cometblue#7]
Sorry, I'm new to HA and probably I'm messing HA terminology.
Since CometBlue has a built-in thermometer could your integration provide also a sensor for current temperature so I can put some graphs on a dashboard?

Thanks

**Comment by neffs** [comment]
The current temperature is available as an attibute in the climate entity: https://developers.home-assistant.io/docs/core/entity/climate (current_temperature). If you need a separate sensor entity you can use a template sensor: https://www.home-assistant.io/integrations/template/

**Comment by DenisBY** [comment]
Thank you!
