### ISSUE TITLE
repo not shown in hacs- Integrations

### ISSUE THREAD

**Issue by 0gordonfreeman** [neffs/ha-cometblue#9]
Hi,
i just tried to add you repo neffs/ha-cometblue to hacs, but it does not exist in the search of the hacs integrations.
HassOS 4.17
Supervisor 2020.11.0

What am i doing wrong?

kind regards, Max

**Comment by neffs** [comment]
Hi Max
you'll have to add this as a custom repository manually.

**Comment by 0gordonfreeman** [comment]
Thanks for your reaction, can you support me by adding/configurate the addon into hacs? (docker version of homeassistant)
instruction in german or english will be perfect.

**Comment by neffs** [comment]
![image](https://user-images.githubusercontent.com/142583/100859856-122ff580-3490-11eb-975e-2d435a3f070e.jpeg)

![image](https://user-images.githubusercontent.com/142583/100859867-152ae600-3490-11eb-91d8-c321aca38277.jpeg)

**Comment by 0gordonfreeman** [comment]
Thanks a lot, it worked.
